<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-37FB485" failures="1" tests="8" name="Default test" time="6.366" errors="0" timestamp="2024-08-15T22:04:04 IST">
  <testcase classname="nodejs_api.Registration_API" name="Existingemail" time="3.764"/>
  <testcase classname="nodejs_api.Registration_API" name="Existingphone" time="0.276"/>
  <testcase classname="nodejs_api.Registration_API" name="emptyemailparameter" time="0.2"/>
  <testcase classname="nodejs_api.Registration_API" name="emptynameparameter" time="0.207"/>
  <testcase classname="nodejs_api.Registration_API" name="emptyphoneparameter" time="0.196"/>
  <testcase classname="nodejs_api.Registration_API" name="invalidemail" time="0.2"/>
  <testcase classname="nodejs_api.Registration_API" name="invalidphone" time="0.22"/>
  <testcase classname="nodejs_api.Registration_API" name="successfulregistration" time="0.238">
    <failure type="java.lang.AssertionError" message="Success message is incorrect expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Success message is incorrect expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at nodejs_api.Registration_API.successfulregistration(Registration_API.java:39)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- successfulregistration -->
</testsuite> <!-- Default test -->
